version: '3.8'

services:
  backend:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - ./:/srv/docker-server/
    env_file:
      - ./.env
    ports:
     - 8000:8000
    working_dir: /srv/docker-server/
    restart: always

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/static/
      - ./certbot/:/etc/letsencrypt/
      - ./certbot/live/:/var/www/
    ports:
      - "80:80"
      - "443:443"
    depends_on :
      - backend
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/:/etc/letsencrypt/
      - ./certbot/live/:/var/www/